name = Fullscreen
description = layout fullscreen
template = fullscreen-layout

; ========================================
; Regions
; ========================================
regions[header] = Header
regions[home] = Home
regions[drawer] = Navigation drawer
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[content] = Content
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layout/fullscreen/fullscreen.layout.css